"""C2 mapping engine against golden statements (plan 0004 step E; AGENT_SPEC §9.2).

Golden outputs (`*.expected.json`) were generated by the engine and checked by
hand against the source XML for the totals the identity checks use; every run
also re-derives each fact's value from its `source_element_path`, independently
of the engine's own walk.
"""

import copy
import json
import re
from collections.abc import Callable
from decimal import Decimal
from pathlib import Path

import pytest
from lxml import etree

from distress_radar.parsing.canonical_schema import MappingConfig
from distress_radar.parsing.containers import Element, safe_parser
from distress_radar.parsing.mapping_engine import MappingError, ParsedStatement, parse_statement
from distress_radar.parsing.version_detection import detect
from distress_radar.parsing.xsd_validation import XsdValidator

FIXTURES_DIR = Path(__file__).parent.parent / "fixtures"
STATEMENTS_DIR = FIXTURES_DIR / "statements"
# Every committed fixture, so a new one is covered without editing this file.
GOLDEN = sorted(STATEMENTS_DIR.glob("*.xml")) + [FIXTURES_DIR / "neobis_001.xml"]
TNS_2018 = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaWZlotych"
TNS_2018_TYS = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaWTysiacach"
JIN_2018 = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/JednostkaInnaStruktury"
DTSF_2018 = "http://www.mf.gov.pl/schematy/SF/DefinicjeTypySprawozdaniaFinansowe/2018/07/09/DefinicjeTypySprawozdaniaFinansowe/"


def load(path: Path) -> etree._Element:
    return etree.fromstring(path.read_bytes(), safe_parser())


def parse(root: etree._Element, config: MappingConfig) -> ParsedStatement:
    detection = detect(root, config)
    assert detection.spec is not None, detection.key
    return parse_statement(root, detection.spec, config)


def expected_path(xml: Path) -> Path:
    return STATEMENTS_DIR / f"{xml.stem}.expected.json"


def as_json(parsed: ParsedStatement) -> dict[str, object]:
    return {
        "structure_version": parsed.structure_version,
        "period_start": parsed.period_start.isoformat(),
        "period_end": parsed.period_end.isoformat(),
        "facts": [
            [
                f.line_item,
                f.column,
                f.statement_type,
                f.variant,
                str(f.value),
                f.source_element_path,
            ]
            for f in parsed.facts
        ],
    }


@pytest.mark.parametrize("xml", GOLDEN, ids=lambda p: p.stem)
def test_golden_statement_matches_expected(xml: Path, mapping_config: MappingConfig) -> None:
    parsed = parse(load(xml), mapping_config)
    assert as_json(parsed) == json.loads(expected_path(xml).read_text(encoding="utf-8"))


@pytest.mark.parametrize("xml", GOLDEN, ids=lambda p: p.stem)
def test_every_fact_resolves_to_its_source_element(
    xml: Path, mapping_config: MappingConfig
) -> None:
    root = load(xml)
    parsed = parse(root, mapping_config)
    spec = mapping_config.specs[parsed.structure_version]
    assert parsed.facts
    for fact in parsed.facts:
        assert isinstance(fact.value, Decimal)
        nodes = root.xpath(fact.source_element_path, namespaces=spec.namespaces)
        assert isinstance(nodes, list) and nodes, fact.source_element_path
        # A user-line total cites every contributing element (an XPath union).
        assert len(nodes) == fact.source_element_path.count(" | ") + 1
        total = sum(
            (Decimal((n.text or "").strip()) for n in nodes if isinstance(n, Element)), Decimal(0)
        )
        assert total * parsed.unit_multiplier == fact.value


def test_identity_totals_by_hand(mapping_config: MappingConfig) -> None:
    """Values read straight from the 2022 golden file, independently of the engine."""
    parsed = parse(load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml"), mapping_config)
    facts = {(f.line_item, f.column): f.value for f in parsed.facts}
    root = load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml")
    ns = {"t": TNS_2018, "j": JIN_2018, "d": DTSF_2018}

    def text(path: str) -> Decimal:
        [node] = root.xpath(path, namespaces=ns)  # type: ignore[misc]
        return Decimal(node.text)  # type: ignore[union-attr]

    assert facts[("BS.ASSETS", "current_year")] == text(
        "/t:JednostkaInna/t:Bilans/j:Aktywa/d:KwotaA"
    )
    assert facts[("BS.EQUITY_LIABILITIES", "prior_year")] == text(
        "/t:JednostkaInna/t:Bilans/j:Pasywa/d:KwotaB"
    )
    assert facts[("IS.COMP.L", "current_year")] == text(
        "/t:JednostkaInna/t:RZiS/j:RZiSPor/j:L/d:KwotaA"
    )
    assert parsed.unit_multiplier == 1


@pytest.mark.parametrize("xml", GOLDEN, ids=lambda p: p.stem)
def test_income_statement_variants_are_never_mixed(
    xml: Path, mapping_config: MappingConfig
) -> None:
    """A document uses exactly one income-statement layout, never two.

    Three exist: the comparative and calculation variants of the full and small
    forms, and the micro form's own single layout, which is neither (ADR 0005
    second addendum §4) and so carries `variant: "n/a"`.
    """
    layouts = {"COMP": "comparative", "CALC": "calculation", "MIKRO": "n/a"}
    parsed = parse(load(xml), mapping_config)
    income = {
        f.line_item.split(".")[1] for f in parsed.facts if f.statement_type == "income_statement"
    }
    assert len(income) == 1 and income <= set(layouts), income
    variants = {f.variant for f in parsed.facts if f.statement_type == "income_statement"}
    assert variants == {layouts[next(iter(income))]}


def test_wariant_2_uses_the_narrowed_codes(mapping_config: MappingConfig) -> None:
    codes = {
        f.line_item
        for f in parse(load(STATEMENTS_DIR / "full_2025_w2_kalk_2025.xml"), mapping_config).facts
    }
    assert "IS.CALC.A.R2025" in codes
    assert "IS.CALC.A" not in codes
    old = {
        f.line_item
        for f in parse(load(STATEMENTS_DIR / "full_2018_v1_2_kalk_2021.xml"), mapping_config).facts
    }
    assert "IS.CALC.A" in old and not any(c.endswith(".R2025") for c in old)


def test_restated_comparatives_column(mapping_config: MappingConfig) -> None:
    parsed = parse(load(STATEMENTS_DIR / "full_2018_v1_0_kalk_b1_2018.xml"), mapping_config)
    assert parsed.structure_version == "full-2018-v1-0"
    assert any(f.column == "prior_year_restated" for f in parsed.facts)


def _retag_to_thousands(root: etree._Element) -> etree._Element:
    """The 2022 golden file rewritten as a JednostkaInnaWTysiacach document."""
    doc = copy.deepcopy(root)
    for el in doc.iter():
        if isinstance(el.tag, str) and etree.QName(el).namespace == TNS_2018:
            el.tag = etree.QName(TNS_2018_TYS, etree.QName(el).localname).text
    doc.tag = etree.QName(TNS_2018_TYS, "JednostkaInnaWTys").text
    kod = doc.find(f".//{{{JIN_2018}}}KodSprawozdania")
    assert kod is not None
    kod.text = "SprFinJednostkaInnaWTysiacach"
    kod.set("kodSystemowy", "SFJINT (1)")
    # Every amount in a thousands document is an integer, including the notes'.
    for el in doc.iter():
        if isinstance(el.tag, str) and el.text and re.fullmatch(r"-?\d+\.\d{2}", el.text.strip()):
            el.text = str(int(Decimal(el.text.strip()) / 1000))
    return doc


def test_thousands_are_normalised_to_zloty(mapping_config: MappingConfig) -> None:
    original = load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml")
    thousands = _retag_to_thousands(original)
    parsed = parse(thousands, mapping_config)
    assert parsed.structure_version == "full-2018-v1-2-tys"
    assert parsed.unit_multiplier == 1000
    raw = Decimal(thousands.find(f".//{{{JIN_2018}}}Aktywa/{{{DTSF_2018}}}KwotaA").text)  # type: ignore[union-attr, arg-type]
    total = next(
        f for f in parsed.facts if (f.line_item, f.column) == ("BS.ASSETS", "current_year")
    )
    assert total.value == raw * 1000
    assert all(f.value % 1000 == 0 for f in parsed.facts)


def test_thousands_fixture_is_schema_valid(
    mapping_config: MappingConfig, validator: XsdValidator
) -> None:
    doc = _retag_to_thousands(load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml"))
    assert validator.validate(doc, mapping_config.specs["full-2018-v1-2-tys"]) == []


def _direct_cash_flow(root: etree._Element) -> etree._Element:
    """Swap the indirect cash flow for a small direct-method one."""
    doc = copy.deepcopy(root)
    cash_flow = doc.find(f"{{{TNS_2018}}}RachPrzeplywow")
    assert cash_flow is not None
    for child in list(cash_flow):
        cash_flow.remove(child)

    def item(parent: etree._Element, name: str, a: str, b: str = "0") -> etree._Element:
        el = etree.SubElement(parent, f"{{{JIN_2018}}}{name}")
        etree.SubElement(el, f"{{{DTSF_2018}}}KwotaA").text = a
        etree.SubElement(el, f"{{{DTSF_2018}}}KwotaB").text = b
        return el

    direct = etree.SubElement(cash_flow, f"{{{JIN_2018}}}PrzeplywyBezp")
    operating = etree.SubElement(direct, f"{{{JIN_2018}}}A")
    item(operating, "A_I", "100.00")
    item(operating, "A_II", "40.00")
    item(operating, "A_III", "60.00")
    item(direct, "D", "60.00")
    item(direct, "F", "10.00")
    item(direct, "G", "70.00")
    return doc


def test_direct_cash_flow_maps_to_direct_codes(mapping_config: MappingConfig) -> None:
    parsed = parse(
        _direct_cash_flow(load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml")), mapping_config
    )
    cash = {
        f.line_item: f
        for f in parsed.facts
        if f.statement_type == "cash_flow" and f.column == "current_year"
    }
    assert set(cash) == {
        "CF.DIR.A.I",
        "CF.DIR.A.II",
        "CF.DIR.A.III",
        "CF.DIR.D",
        "CF.DIR.F",
        "CF.DIR.G",
    }
    assert {f.variant for f in cash.values()} == {"direct"}
    assert cash["CF.DIR.A.III"].value == Decimal("60.00")


Mutation = Callable[[etree._Element], None]


def _mutated(mutate: Mutation) -> etree._Element:
    root = load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml")
    mutate(root)
    return root


def _remove(root: etree._Element, path: str) -> None:
    ns = {"t": TNS_2018, "j": JIN_2018, "d": DTSF_2018}
    for node in root.xpath(path, namespaces=ns):  # type: ignore[union-attr]
        node.getparent().remove(node)  # type: ignore[union-attr]


def _set(root: etree._Element, path: str, value: str) -> None:
    ns = {"t": TNS_2018, "j": JIN_2018, "d": DTSF_2018}
    [node] = root.xpath(path, namespaces=ns)  # type: ignore[misc]
    node.text = value  # type: ignore[union-attr]


def _add_second_variant(root: etree._Element) -> None:
    rzis = root.find(f"{{{TNS_2018}}}RZiS")
    assert rzis is not None
    etree.SubElement(rzis, f"{{{JIN_2018}}}RZiSKalk")


@pytest.mark.parametrize(
    ("mutate", "reason"),
    [
        (lambda r: _remove(r, "/t:JednostkaInna/t:Bilans"), "required_statement_missing"),
        (lambda r: _remove(r, "/t:JednostkaInna/t:Bilans/j:Pasywa"), "required_item_missing"),
        (
            lambda r: _set(r, "/t:JednostkaInna/t:Naglowek/j:KodSprawozdania", "SprFinCosInnego"),
            "unit_unrecognised",
        ),
        (
            lambda r: _set(r, "/t:JednostkaInna/t:Bilans/j:Aktywa/d:KwotaA", "12,50"),
            "amount_malformed",
        ),
        (
            lambda r: _set(r, "/t:JednostkaInna/t:Bilans/j:Aktywa/d:KwotaA", "12.505"),
            "amount_malformed",
        ),
        (
            lambda r: _set(r, "/t:JednostkaInna/t:Naglowek/d:OkresDo", "2021-01-01"),
            "header_malformed",
        ),
        (_add_second_variant, "statement_variant_ambiguous"),
    ],
)
def test_untrustworthy_documents_raise(
    mutate: Mutation, reason: str, mapping_config: MappingConfig
) -> None:
    root = _mutated(mutate)
    with pytest.raises(MappingError) as info:
        parse(root, mapping_config)
    assert info.value.reason_code == reason


def test_absent_optional_item_yields_no_fact(mapping_config: MappingConfig) -> None:
    full = parse(load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml"), mapping_config)
    leaf = "/t:JednostkaInna/t:Bilans/j:Pasywa/j:Pasywa_B/j:Pasywa_B_III/j:Pasywa_B_III_3/j:Pasywa_B_III_3_I"
    without = parse(_mutated(lambda r: _remove(r, leaf)), mapping_config)
    removed = {(f.line_item, f.column) for f in full.facts} - {
        (f.line_item, f.column) for f in without.facts
    }
    assert removed == {
        ("BS.EQUITY_LIABILITIES.B.III.3.I", "current_year"),
        ("BS.EQUITY_LIABILITIES.B.III.3.I", "prior_year"),
    }
    assert len(without.facts) == len(full.facts) - 2


def test_optional_statements_may_be_absent(mapping_config: MappingConfig) -> None:
    parsed = parse(
        _mutated(
            lambda r: _remove(
                r, "/t:JednostkaInna/t:RachPrzeplywow | /t:JednostkaInna/t:ZestZmianWKapitale"
            )
        ),
        mapping_config,
    )
    assert {f.statement_type for f in parsed.facts} == {"balance_sheet", "income_statement"}


def _add_user_line(parent: etree._Element, slot: int, amount: str) -> None:
    line = etree.SubElement(parent, f"{{{JIN_2018}}}PozycjaUszczegolawiajaca_{slot}")
    etree.SubElement(line, f"{{{DTSF_2018}}}NazwaPozycji").text = "Podróże służbowe"
    amounts = etree.SubElement(line, f"{{{DTSF_2018}}}KwotyPozycji")
    etree.SubElement(amounts, f"{{{DTSF_2018}}}KwotaA").text = amount
    etree.SubElement(amounts, f"{{{DTSF_2018}}}KwotaB").text = "0.00"


def test_user_lines_are_summed_into_one_fact(mapping_config: MappingConfig) -> None:
    root = load(STATEMENTS_DIR / "full_2018_v1_2_por_2022.xml")
    costs = root.find(f".//{{{JIN_2018}}}RZiSPor/{{{JIN_2018}}}B")
    assert costs is not None
    _add_user_line(costs, 7, "100.00")
    _add_user_line(costs, 7, "23.45")
    _add_user_line(costs, 9, "1.00")
    parsed = parse(root, mapping_config)
    [fact] = [
        f for f in parsed.facts if (f.line_item, f.column) == ("IS.COMP.B.USER", "current_year")
    ]
    assert fact.value == Decimal("124.45")
    assert fact.source_element_path.count(" | ") == 2
    assert "PozycjaUszczegolawiajaca_7[2]" in fact.source_element_path
